- name: Update apt repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Upgrade all pkg
  apt:
    upgrade: dist
    force_apt_get: yes

- name: Cleaning -autoremove- pkg 
  apt:
    autoremove: yes

- name: Check if restart is required
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=no

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes
