- name: Create user: pentester, with pass: 1234
  user:
      name: pentester
      shell: "/bin/bash"
      createhome: yes
      generate_ssh_key: yes
      ssh_key_bits: 2048
      # zmien haslo 1234
      password: "{{ '1234' | password_hash('sha512') }}"
      update_password: always

- name: add to groups recon
  # szuka uzytkownika kali
  shell: 'user=kali; cat /etc/group | grep $user | cut -d ":" -f 1 | sort | uniq | grep -v -w $user'      
  register: user_groups

- name: add to groups
  ansible.builtin.user:
      name: pentester
      shell: "/bin/bash"
      groups: '{{ user_groups.stdout_lines }}'
      append: yes

- name: Add user to sudoers file
  lineinfile:
      path: /etc/sudoers
      regexp: '^pentester'
      line: 'pentester ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
