- name: Utworzenie uzytkownika pentester
  user:
      name: pentester
      shell: "/bin/bash"
      createhome: yes
      generate_ssh_key: yes
      ssh_key_bits: 2048
      # zmień hasło
      password: "{{ '1234' | password_hash('sha512') }}"
      update_password: always

- name: przypisanie grup dla nowego uzytkownika
  # szuka uzytkownika kali
  shell: 'user=kali; cat /etc/group | grep $user | cut -d ":" -f 1 | sort | uniq | grep -v -w $user'      
  register: user_groups

- name: przypisanie
  ansible.builtin.user:
      name: pentester
      shell: "/bin/bash"
      groups: '{{ user_groups.stdout_lines }}'
      append: yes
