- hosts: localhost
  vars: 
     package_names:
      - kali-linux-everything
      - telnet
      - nano 
      - metasploit-framework
      - python3
      - python3-apt
      - iptraf-ng
      - xfce4 
      - xfce4-goodies 
      - xorg 
      - dbus-x11 
      - x11-xserver-utils
      - xrdp
  become_user: root
  tasks:
#DEBIAN
    - name: Sprawdz zainstalowanie pakiety na hoscie Kali
      command: dpkg-query -l "{{ item }}"
      loop: "{{ package_names }}"
      register: debian_package_check
      when: ansible_facts['os_family'] == "Debian"

    - name: Instaluj jak pakietu nie ma hoscie Kali
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ package_names }}"
      when: debian_package_check is failed and ansible_facts['os_family'] == "Debian"
      
      - name: Install a .deb package from the internet
        ansible.builtin.apt:
        deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64

      - name: Remove useless packages from the cache
        ansible.builtin.apt:
          autoclean: yes

      - name: Remove dependencies that are no longer required
        ansible.builtin.apt:
          autoremove: yes

      - name: Run the equivalent of "apt-get clean" as a separate step
        apt:
          clean: yes
      
      - name: "Ustawiamy na stałe podniesiona usluge SSH"
          shell: "systemctl enable ssh.service"
          
      - name: "Podnosimy usługę SSH"
          shell: "systemctl start ssh.service"
          
      - name: "Ustawiamy na stałe podniesiona usluge XRDP"
          shell: "systemctl enable xrdp"
          
      - name: "Podnosimy usługę XRDP"
          shell: "systemctl start xrdp"
