- hosts: kali
  become_user: root
  tasks:
    - name: Aktualizacja apt repo i cache na wszystkich maszynkach KALI
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade wszystkich pakietow na maszynkach KALI
      apt: upgrade=dist force_apt_get=yes

    - name: Sprawdzam czy wymagany jest restart
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no
